-- ============================================================
-- Catálogo de modelos de imagen/video (provider comfy)
--
-- GENERADO por scripts/generate-media-models-sql.mjs desde el catálogo vivo
-- del comfy-bridge el 2026-08-02. No editar a mano: volvé a generarlo.
--
-- Precio: 500 créditos por imagen y 3000 por clip en la configuración
-- de referencia (1MP y los steps por defecto de cada modelo); escala con
-- píxeles/steps/frames en src/lib/media-credits.ts.
-- ============================================================

INSERT INTO models (
  id, provider, upstream_model_id, display_name,
  cost_per_m_input, cost_per_m_output, margin,
  is_active, context_length, capabilities,
  modality, media_base_credits, media_base_pixels, media_base_steps, media_base_frames, media_config
) VALUES
  ('vid/wan-2.2-5b', 'comfy', 'wan-2.2-5b', 'Wan 2.2 TI2V 5B (video)', 0, 0, 1.0, true, NULL, '["video_generation"]'::jsonb, 'video', 3000, 901120, 30, 49, '{"defaults":{"width":1280,"height":704,"length":49,"fps":24,"steps":30,"cfg":5,"shift":8,"sampler":"uni_pc","scheduler":"simple","denoise":1,"negative_prompt":"低质量, 模糊, 静止不动, 变形, 多余的手指, 画面暗淡, overexposed, static, blurry, low quality"},"limits":{"maxSteps":40,"maxPixels":901120,"maxLength":121,"maxBatch":1},"supports":{"negative":true,"i2v":true,"loras":false}}'::jsonb),
  ('img/jankuv5-trained-noobai-v50', 'comfy', 'jankuv5-trained-noobai-v50', 'JANKUV5 Trained Noobai v50', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/vidroh-h-v1-2', 'comfy', 'vidroh-h-v1-2', 'Vidrohằh-v1.2', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/anicorexl-illustriouss-v7', 'comfy', 'anicorexl-illustriouss-v7', 'anicorexl illustriouss v7', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/animayhem-pale-rider-v30-plains-drifter', 'comfy', 'animayhem-pale-rider-v30-plains-drifter', 'animayhem Pale Rider v30 Plains Drifter', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/animij-v7', 'comfy', 'animij-v7', 'animij v7', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/hassaku-xlillustrious-v13-style-a', 'comfy', 'hassaku-xlillustrious-v13-style-a', 'Hassaku XL v1.3 Style A (anime)', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/hassaku-xlillustrious-v22', 'comfy', 'hassaku-xlillustrious-v22', 'Hassaku XL v2.2 (anime)', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/illustrious-realism-by-v10-vae', 'comfy', 'illustrious-realism-by-v10-vae', 'Illustrious Realism v1', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/illustrious-xl-v01', 'comfy', 'illustrious-xl-v01', 'Illustrious XL v0.1 (base anime)', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/iris-lux-polyvalent-prototype-v1051-vaeincluded', 'comfy', 'iris-lux-polyvalent-prototype-v1051-vaeincluded', 'iris Lux Polyvalent Prototype v1051 VAEIncluded', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/realism-xl', 'comfy', 'juggernaut-xl-ragnarok-by', 'Juggernaut XL Ragnarok (realismo)', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 30, NULL, '{"defaults":{"width":1024,"height":1024,"steps":30,"cfg":4.5,"sampler":"dpmpp_2m","scheduler":"karras","negative_prompt":"worst quality, low quality, blurry, deformed, watermark, text","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/nova3-dcgxl-il-v90', 'comfy', 'nova3-dcgxl-il-v90', 'Nova 3DCG XL v9 (3D)', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/nova-orange-xl-re-v30', 'comfy', 'nova-orange-xl-re-v30', 'Nova Orange XL v3', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/ntr-mixillustrious-xl-xiii', 'comfy', 'ntr-mixillustrious-xl-xiii', 'ntr MIXIllustrious XL xiii', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/one-obsession-branch-mature-maxeps', 'comfy', 'one-obsession-branch-mature-maxeps', 'one Obsession Branch mature MAXEPS', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/one-obsession-branch-v7-matureeps', 'comfy', 'one-obsession-branch-v7-matureeps', 'one Obsession Branch v7 Matureeps', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/perfectdeliberate-v20-a', 'comfy', 'perfectdeliberate-v20-a', 'perfectdeliberate v20 A', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 30, NULL, '{"defaults":{"width":1024,"height":1024,"steps":30,"cfg":4.5,"sampler":"dpmpp_2m","scheduler":"karras","negative_prompt":"worst quality, low quality, blurry, deformed, watermark, text","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/perfectdeliberate-v8', 'comfy', 'perfectdeliberate-v8', 'perfectdeliberate v8', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 30, NULL, '{"defaults":{"width":1024,"height":1024,"steps":30,"cfg":4.5,"sampler":"dpmpp_2m","scheduler":"karras","negative_prompt":"worst quality, low quality, blurry, deformed, watermark, text","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/prefect-illustrious-xl-v20p', 'comfy', 'prefect-illustrious-xl-v20p', 'prefect Illustrious XL v20p', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/prefect-illustrious-xl-v3', 'comfy', 'prefect-illustrious-xl-v3', 'prefect Illustrious XL v3', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/prefect-illustrious-xl-v70', 'comfy', 'prefect-illustrious-xl-v70', 'Prefect Illustrious v7 (anime)', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/realism-xl-fast', 'comfy', 'realvisxl-v50-v50-lightning-bakedvae', 'RealVis XL v5 Lightning (rápido)', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 6, NULL, '{"defaults":{"width":1024,"height":1024,"steps":6,"cfg":1.5,"sampler":"dpmpp_sde","scheduler":"karras","negative_prompt":"worst quality, low quality, blurry, deformed, watermark, text","denoise":1},"limits":{"maxSteps":14,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/sd-xl-base-1-0', 'comfy', 'sd-xl-base-1-0', 'SDXL Base 1.0', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 30, NULL, '{"defaults":{"width":1024,"height":1024,"steps":30,"cfg":4.5,"sampler":"dpmpp_2m","scheduler":"karras","negative_prompt":"worst quality, low quality, blurry, deformed, watermark, text","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/unholy-desire-mix-sinister-v50', 'comfy', 'unholy-desire-mix-sinister-v50', 'unholy Desire Mix Sinister v50', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/wai-illustrious-sdxl-v130', 'comfy', 'wai-illustrious-sdxl-v130', 'WAI Illustrious v13 (anime)', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/anime-xl', 'comfy', 'wai-illustrious-sdxl-v150', 'WAI Illustrious v15 (anime)', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 28, NULL, '{"defaults":{"width":832,"height":1216,"steps":28,"cfg":5,"sampler":"euler_ancestral","scheduler":"normal","negative_prompt":"worst quality, low quality, lowres, jpeg artifacts, bad anatomy, bad hands, watermark, signature","denoise":1},"limits":{"maxSteps":60,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":true,"img2img":true,"loras":true}}'::jsonb),
  ('img/flux-dev', 'comfy', 'flux-dev', 'FLUX.1 dev', 0, 0, 1.0, true, NULL, '["image_generation"]'::jsonb, 'image', 500, 1048576, 20, NULL, '{"defaults":{"width":1024,"height":1024,"steps":20,"cfg":1,"guidance":3.5,"sampler":"euler","scheduler":"simple","denoise":1},"limits":{"maxSteps":50,"maxPixels":2359296,"maxBatch":4},"supports":{"negative":false,"img2img":true,"loras":true}}'::jsonb)
ON CONFLICT (id) DO UPDATE
SET provider           = EXCLUDED.provider,
    upstream_model_id  = EXCLUDED.upstream_model_id,
    display_name       = EXCLUDED.display_name,
    capabilities       = EXCLUDED.capabilities,
    modality           = EXCLUDED.modality,
    media_base_credits = EXCLUDED.media_base_credits,
    media_base_pixels  = EXCLUDED.media_base_pixels,
    media_base_steps   = EXCLUDED.media_base_steps,
    media_base_frames  = EXCLUDED.media_base_frames,
    media_config       = EXCLUDED.media_config;

-- Un checkpoint borrado de la PC no debe quedar ofertado en el catálogo.
UPDATE models
SET is_active = false
WHERE provider = 'comfy'
  AND upstream_model_id NOT IN ('wan-2.2-5b', 'jankuv5-trained-noobai-v50', 'vidroh-h-v1-2', 'anicorexl-illustriouss-v7', 'animayhem-pale-rider-v30-plains-drifter', 'animij-v7', 'hassaku-xlillustrious-v13-style-a', 'hassaku-xlillustrious-v22', 'illustrious-realism-by-v10-vae', 'illustrious-xl-v01', 'iris-lux-polyvalent-prototype-v1051-vaeincluded', 'juggernaut-xl-ragnarok-by', 'nova3-dcgxl-il-v90', 'nova-orange-xl-re-v30', 'ntr-mixillustrious-xl-xiii', 'one-obsession-branch-mature-maxeps', 'one-obsession-branch-v7-matureeps', 'perfectdeliberate-v20-a', 'perfectdeliberate-v8', 'prefect-illustrious-xl-v20p', 'prefect-illustrious-xl-v3', 'prefect-illustrious-xl-v70', 'realvisxl-v50-v50-lightning-bakedvae', 'sd-xl-base-1-0', 'unholy-desire-mix-sinister-v50', 'wai-illustrious-sdxl-v130', 'wai-illustrious-sdxl-v150', 'flux-dev');
